In [2]:
from openai import OpenAI
from dotenv import load_dotenv
import pandas as pd
load_dotenv()

from ingestion import get_transcripts_dataframe, build_index
openai_client = OpenAI()

## Ingestion

In [3]:
documents_df = get_transcripts_dataframe()
index = build_index(documents_df)

## RAG Flow

In [13]:
from rag_helper import RAGBase

assistant = RAGBase(
    index=index,
    llm_client=openai_client,
)

In [5]:
print(assistant.rag("Which techniques can help improve self-awareness?"))

Techniques that can help improve self-awareness include:
- Recording yourself and reviewing your gestures, posture, tone, and speaking habits
- Asking yourself what causes your stress, who triggers it, and when it happens
- Questioning your emotions, such as why you feel afraid, guilty, sad, angry, or irritated, and what caused them

https://www.youtube.com/watch?v=ln8rIBZbWAE

## Evaluation

### Search Evaluation

In [4]:
df_ground_truth = pd.read_csv("data/ground_truth.csv")

In [5]:
ground_truth = df_ground_truth.to_dict(orient="records")

In [6]:
documents_llm = []

for doc in documents_df:
    documents_llm.append(doc)

documents = documents_llm

In [50]:
def text_search(query):
    boost_dict = { "video_id": 10}

    return index.search(
        query,
        num_results=5,
        boost_dict=boost_dict
    )

In [42]:
q = ground_truth[0]
q

{'question': 'How is emotional intelligence defined in simple terms?',
 'document': 0}

In [51]:
doc_id = q['document']
doc_id

0

In [52]:
results = text_search(q['question'])
results

[{'id': 0,
  'question': 'What is emotional intelligence?',
  'answer': 'Emotional intelligence is how effectively you handle yourself, your emotions, and your relationships with other people.',
  'video_id': 'BqF50IuR3_c'},
 {'id': 81,
  'question': 'What does intelligence mean in terms of adaptation?',
  'answer': 'Intelligence is the capacity to adapt effectively to different situations.',
  'video_id': 'f_sqTkn2A-c'},
 {'id': 60,
  'question': 'How is emotional intelligence connected to everyday life?',
  'answer': 'Emotional intelligence affects how effectively you manage yourself and interact with other people.',
  'video_id': 'Y7m9eNoB3NU'},
 {'id': 12,
  'question': 'What is relationship management in emotional intelligence?',
  'answer': 'Relationship management means combining self-awareness, self-management, and empathy to interact skillfully with others.',
  'video_id': 'BqF50IuR3_c'},
 {'id': 78,
  'question': 'How does developing emotional intelligence affect your strengths?',
  'answer': 'As you develop your skills, you can acquire strengths in the emotional areas you need to become more effective.',
  'video_id': 'Y7m9eNoB3NU'}]

In [53]:
for d in results:
    print(f'{d["id"]} == {doc_id}: {d["id"] == doc_id}')

0 == 0: True
81 == 0: False
60 == 0: False
12 == 0: False
78 == 0: False

In [54]:
relevance = []

for d in results:
    relevance.append(int(d["id"] == doc_id))

relevance

[1, 0, 0, 0, 0]

In [13]:
def compute_relevance_text(q):
    doc_id = q["document"]
    results = text_search(query=q["question"])

    relevance = []
    for d in results:
        relevance.append(int(d["id"] == doc_id))

    return relevance

In [16]:
from tqdm.auto import tqdm

def compute_relevance_total_text(ground_truth):
    relevance_total = []

    for q in tqdm(ground_truth):
        relevance = compute_relevance_text(q)
        relevance_total.append(relevance)

    return relevance_total

In [17]:
relevance = compute_relevance_total_text(ground_truth)

  0%|          | 0/500 [00:00<?, ?it/s]

In [19]:
def compute_relevance(q, search_function):
    doc_id = q["document"]
    results = search_function(query=q["question"])

    relevance = []
    for d in results:
        relevance.append(int(d["id"] == doc_id))

    return relevance

In [20]:
def compute_relevance_total(ground_truth, search_function):
    relevance_total = []

    for q in tqdm(ground_truth):
        relevance = compute_relevance(q, search_function)
        relevance_total.append(relevance)

    return relevance_total

In [21]:
relevance_total = compute_relevance_total(ground_truth, text_search)

  0%|          | 0/500 [00:00<?, ?it/s]

In [23]:
def hit_rate(relevance):
    cnt = 0

    for line in relevance:
        if 1 in line:
            cnt = cnt + 1

    return cnt / len(relevance)

In [25]:
def mrr(relevance):
    total_score = 0.0

    for line in relevance:
        for rank in range(len(line)):
            if line[rank] == 1:
                score = 1 / (rank + 1)
                total_score = total_score + score
                break

    return total_score / len(relevance)

In [ ]:
def evaluate(ground_truth, search_function):
    relevance_total = compute_relevance_total(ground_truth, search_function)

    return {
        "hit_rate": hit_rate(relevance_total),
        "mrr": mrr(relevance_total),
    }

In [36]:
def search_boosts(query, question_boost, answer_boost, video_id):
    boost_dict = {
        "question": question_boost,
        "video_id": video_id,
        "answer": answer_boost,
    }

    return index.search(
        query,
        num_results=5,
        boost_dict=boost_dict,
    )

In [39]:
results_search_evaluation = []

for question_boost in [1.0, 2.0, 5.0]:
    for answer_boost in [1.0, 2.0, 4.0, 10.0]:
        for video_id in [0.1, 0.2, 0.5]:
            print(f"Evaluating question_boost={question_boost}, answer_boost={answer_boost}, video_id={video_id}...")
            results_search_evaluation_dict = evaluate(
                ground_truth,
                lambda query, question_boost=question_boost, answer_boost=answer_boost, video_id=video_id: search_boosts(
                    query,
                    question_boost,
                    answer_boost,
                    video_id
                )
            )

            results_search_evaluation.append({
                "question": question_boost,
                "answer": answer_boost,
                "video_id": video_id,
                "hit_rate": results_search_evaluation_dict["hit_rate"],
                "mrr": results_search_evaluation_dict["mrr"],
            })

Evaluating question_boost=1.0, answer_boost=1.0, video_id=0.1...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=1.0, video_id=0.2...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=1.0, video_id=0.5...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=2.0, video_id=0.1...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=2.0, video_id=0.2...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=2.0, video_id=0.5...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=4.0, video_id=0.1...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=4.0, video_id=0.2...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=4.0, video_id=0.5...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=10.0, video_id=0.1...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=10.0, video_id=0.2...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=1.0, answer_boost=10.0, video_id=0.5...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=1.0, video_id=0.1...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=1.0, video_id=0.2...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=1.0, video_id=0.5...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=2.0, video_id=0.1...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=2.0, video_id=0.2...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=2.0, video_id=0.5...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=4.0, video_id=0.1...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=4.0, video_id=0.2...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=4.0, video_id=0.5...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=10.0, video_id=0.1...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=10.0, video_id=0.2...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=2.0, answer_boost=10.0, video_id=0.5...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=1.0, video_id=0.1...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=1.0, video_id=0.2...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=1.0, video_id=0.5...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=2.0, video_id=0.1...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=2.0, video_id=0.2...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=2.0, video_id=0.5...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=4.0, video_id=0.1...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=4.0, video_id=0.2...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=4.0, video_id=0.5...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=10.0, video_id=0.1...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=10.0, video_id=0.2...

  0%|          | 0/500 [00:00<?, ?it/s]

Evaluating question_boost=5.0, answer_boost=10.0, video_id=0.5...

  0%|          | 0/500 [00:00<?, ?it/s]

In [40]:
df_results = pd.DataFrame(results_search_evaluation)
df_results.sort_values("mrr", ascending=False).head(10)

    question  answer  video_id  hit_rate       mrr
3        1.0     2.0       0.1     0.868  0.739467
19       2.0     4.0       0.2     0.868  0.739467
5        1.0     2.0       0.5     0.868  0.739467
4        1.0     2.0       0.2     0.868  0.739467
34       5.0    10.0       0.2     0.868  0.739467
35       5.0    10.0       0.5     0.868  0.739467
33       5.0    10.0       0.1     0.868  0.739467
18       2.0     4.0       0.1     0.868  0.739467
20       2.0     4.0       0.5     0.868  0.739467
2        1.0     1.0       0.5     0.864  0.737667

Conclusion : 
- question: 1.0	
- answer: 2.0	
- video_id: 0.1

### Generating RAG Answers

In [73]:
import pandas as pd

df_ground_truth = pd.read_csv("data/ground_truth.csv")
ground_truth = df_ground_truth.to_dict(orient="records")

In [74]:
documents_list = []

for doc in documents_df:
    documents_list.append(doc)

In [75]:
doc_idx = {}

for doc in documents_list:
    doc_idx[doc["id"]] = doc

In [76]:
INSTRUCTIONS_EVALUATION = """
You are a helpful assistant that answers questions regarding self-awareness based on the provided context.

Use the context to find relevant information and provide accurate
answers. 
If the answer is not found in the context,
respond with "I don't know."
"""

assistant_evaluation = RAGBase(
    index=index,
    llm_client=openai_client,
    instructions=INSTRUCTIONS_EVALUATION,
)

In [77]:
def generate_rag_answer(rec):
    question = rec["question"]
    doc_id = rec["document"]
    original_doc = doc_idx[doc_id]

    answer_llm = assistant_evaluation.rag(question)
    answer_orig = original_doc["answer"]

    result = {
        "question": question,
        "answer_llm": answer_llm,
        "answer_orig": answer_orig,
        "document": doc_id,
    }

    return result

In [78]:
from concurrent.futures import ThreadPoolExecutor
from evaluation_utils import map_progress

In [ ]:
with ThreadPoolExecutor(max_workers=6) as pool:
    results = map_progress(pool, ground_truth, generate_rag_answer)

  0%|          | 0/500 [00:00<?, ?it/s]

In [ ]:
df_results = pd.DataFrame(results)

In [ ]:
df_results.head()

,question,answer_llm,answer_orig,document
0,What does emotional intelligence mean in simpl...,Emotional intelligence means how well you hand...,Emotional intelligence is how effectively you ...,0
1,How does emotional intelligence affect the way...,Emotional intelligence helps you handle yourse...,Emotional intelligence is how effectively you ...,0
2,Why is emotional intelligence important in rel...,Emotional intelligence is important in relatio...,Emotional intelligence is how effectively you ...,0
3,What skills are included in emotional intellig...,The four main domains of emotional intelligenc...,Emotional intelligence is how effectively you ...,0
4,How would you explain emotional intelligence t...,Emotional intelligence is how effectively you ...,Emotional intelligence is how effectively you ...,0

In [ ]:
df_results.to_csv("data/rag-answers.csv", index=False)

### LLM AS A JUDGE

In [51]:
from pydantic import BaseModel, Field
from typing import Literal

class AnswerEvaluation(BaseModel):
    reasoning: str = Field(
        description="Reasoning about the quality of the answer."
    )
    score: Literal["good", "bad"] = Field(
        description="'good' if the answer is correct and complete, 'bad' otherwise."
    )

In [52]:
aqa_judge_instructions = """
You are an expert evaluator. You will be given:
1. A question from a user that wants to know about self-awareness
2. The original answer from the dataset (ground truth)
3. An answer generated by an AI assistant

Your task is to decide if the AI answer is semantically equivalent to
the original answer.

Rules:
- The AI answer does NOT need to be word-for-word identical
- It should convey the same key information
- Extra detail is fine as long as the core answer is correct
- Mark 'bad' only if the AI answer is wrong or misses the key point

Be fair and focus on correctness, not style.
""".strip()

In [53]:
aqa_judge_prompt = """
Question:
{question}

Original Answer (ground truth):
{answer_orig}

AI Answer:
{answer_llm}
""".strip()

In [54]:
answers = df_results.to_dict(orient="records")

In [55]:
from evaluation_utils import calc_price, calc_total_price, llm_structured_retry, map_progress

def evaluate_aqa(question, answer_orig, answer_llm, model="gpt-5.4-mini"):
    prompt = aqa_judge_prompt.format(
        question=question,
        answer_orig=answer_orig,
        answer_llm=answer_llm
    )

    result, usage = llm_structured_retry(
        openai_client,
        aqa_judge_instructions,
        prompt,
        AnswerEvaluation,
        model=model,
    )

    return result, usage

In [56]:
def judge_record(rec):
    eval_result, usage = evaluate_aqa(
        question=rec["question"],
        answer_orig=rec["answer_orig"],
        answer_llm=rec["answer_llm"]
    )

    result = {
        "question": rec["question"],
        "document": rec["document"],
        "score": eval_result.score,
        "reasoning": eval_result.reasoning,
    }

    return result, usage

In [57]:
from concurrent.futures import ThreadPoolExecutor

with ThreadPoolExecutor(max_workers=6) as pool:
    results_evaluation = map_progress(pool, answers, judge_record)

  0%|          | 0/500 [00:00<?, ?it/s]

In [58]:
results_evaluation

[({'question': 'What does emotional intelligence mean in simple terms?',
   'document': 0,
   'score': 'good',
   'reasoning': "The AI answer preserves the exact meaning of the ground truth: it defines emotional intelligence as effectively handling oneself, one's emotions, and relationships with others. The wording differs slightly ('how well' vs 'how effectively'), but the semantic content is the same."},
  ResponseUsage(input_tokens=283, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=66, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=349)),
 ({'question': 'How does emotional intelligence affect the way you handle your own emotions?',
   'document': 0,
   'score': 'good',
   'reasoning': 'The AI answer captures the main idea of the ground truth: emotional intelligence is about handling yourself and your emotions effectively. It omits the part about relationships with other people, but the question asks specifically about handling your own emotions, so the omission does not change the core meaning in this context.'},
  ResponseUsage(input_tokens=280, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=74, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=354)),
 ({'question': 'Why is emotional intelligence important in relationships with other people?',
   'document': 0,
   'score': 'good',
   'reasoning': 'The AI answer preserves the core meaning of the original: emotional intelligence involves managing oneself, emotions, and relationships with other people. It is semantically equivalent, with only minor rephrasing.'},
  ResponseUsage(input_tokens=289, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=54, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=343)),
 ({'question': 'What skills are included in emotional intelligence besides self-control?',
   'document': 0,
   'score': 'good',
   'reasoning': 'The ground truth asks what skills are included in emotional intelligence besides self-control. The AI answer lists the standard four domains and includes self-management (which corresponds to self-control) plus the other domains: self-awareness, empathy, and relationship management. This matches the intended information and addresses the question appropriately, though it is more specific than the ground truth.'},
  ResponseUsage(input_tokens=287, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=85, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=372)),
 ({'question': 'How would you explain emotional intelligence to someone who has never heard of it?',
   'document': 0,
   'score': 'good',
   'reasoning': 'The AI answer preserves the core definition from the ground truth exactly and adds a reasonable elaboration about recognizing and managing emotions. This is semantically equivalent and correct.'},
  ResponseUsage(input_tokens=313, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=48, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=361)),
 ({'question': 'What are the four main parts of emotional intelligence?',
   'document': 1,
   'score': 'good',
   'reasoning': 'The AI answer exactly matches the ground truth by listing the same four domains of emotional intelligence: self-awareness, self-management, empathy, and relationship management.'},
  ResponseUsage(input_tokens=282, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=46, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=328)),
 ({'question': 'Which four domains make up emotional intelligence?',
   'document': 1,
   'score': 'good',
   'reasoning': 'The AI answer exactly matches the ground truth and includes all four domains of emotional intelligence: self-awareness, self-management, empathy, and relationship management.'},
  ResponseUsage(input_tokens=274, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=45, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=319)),
 ({'question': 'Can you list the four core areas of emotional intelligence?',
   'document': 1,
   'score': 'good',
   'reasoning': 'The AI answer exactly matches the ground truth by listing the same four domains of emotional intelligence: self-awareness, self-management, empathy, and relationship management.'},
  ResponseUsage(input_tokens=283, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=46, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=329)),
 ({'question': 'What are the key domains included in emotional intelligence?',
   'document': 1,
   'score': 'good',
   'reasoning': 'The AI answer exactly matches the ground truth by listing the four domains of emotional intelligence: self-awareness, self-management, empathy, and relationship management.'},
  ResponseUsage(input_tokens=278, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=45, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=323)),
 ({'question': 'What are the four main emotional intelligence skills?',
   'document': 1,
   'score': 'good',
   'reasoning': 'The AI answer exactly matches the ground truth by listing the same four emotional intelligence domains: self-awareness, self-management, empathy, and relationship management.'},
  ResponseUsage(input_tokens=280, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=45, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=325)),
 ({'question': 'What does it mean to be self-aware?',
   'document': 2,
   'score': 'good',
   'reasoning': 'The AI answer matches the ground truth exactly and conveys the same definition of self-awareness.'},
  ResponseUsage(input_tokens=277, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=33, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=310)),
 ({'question': 'How would you explain self-awareness in simple terms?',
   'document': 2,
   'score': 'good',
   'reasoning': 'The AI answer conveys the core idea of self-awareness: noticing your internal states and understanding their effects. This matches the ground truth’s emphasis on recognizing what you are feeling and why you are feeling it. It adds thoughts and behavior, which is fine and consistent with the concept.'},
  ResponseUsage(input_tokens=298, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=71, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=369)),
 ({'question': 'What does it involve when someone is self-aware?',
   'document': 2,
   'score': 'good',
   'reasoning': "The AI answer matches the ground truth exactly in meaning and wording. It correctly states that self-awareness involves recognizing one's feelings and understanding why one is feeling them."},
  ResponseUsage(input_tokens=278, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=47, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=325)),
 ({'question': 'Why is being self-aware about noticing your feelings and knowing why they happen?',
   'document': 2,
   'score': 'good',
   'reasoning': 'The AI answer matches the ground truth exactly in its core definition: self-awareness is recognizing what you are feeling and understanding why you are feeling it. The added sentence is consistent and does not change the meaning.'},
  ResponseUsage(input_tokens=302, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=57, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=359)),
 ({'question': 'In what way does self-awareness help you understand what you feel and the reason behind it?',
   'document': 2,
   'score': 'good',
   'reasoning': 'The AI answer matches the ground truth in meaning: it states that self-awareness helps you recognize your feelings and understand the reasons behind them. This is semantically equivalent.'},
  ResponseUsage(input_tokens=286, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=49, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=335)),
 ({'question': 'How can self-awareness improve your intuition?',
   'document': 3,
   'score': 'good',
   'reasoning': 'The AI answer matches the ground truth exactly and conveys the same key idea: self-awareness helps intuition by making your emotions and their causes useful internal information.'},
  ResponseUsage(input_tokens=276, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=46, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=322)),
 ({'question': 'Why does understanding your emotions and their causes help intuition?',
   'document': 3,
   'score': 'good',
   'reasoning': 'The AI answer exactly matches the original answer and preserves the same meaning and key information.'},
  ResponseUsage(input_tokens=279, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=33, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=312)),
 ({'question': 'What kind of internal information comes from being aware of your emotions?',
   'document': 3,
   'score': 'good',
   'reasoning': 'The AI answer exactly matches the original answer in meaning and wording. It correctly states that understanding your emotions and their causes provides useful internal information that supports intuition.'},
  ResponseUsage(input_tokens=281, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=47, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=328)),
 ({'question': 'Can knowing why I feel a certain way make my gut feelings better?',
   'document': 3,
   'score': 'good',
   'reasoning': 'The AI answer preserves the core idea of the ground truth: understanding the causes of your emotions can provide useful information that supports intuition/gut feelings. It adds reasonable elaboration about managing emotions and judgment, which is consistent with the original meaning.'},
  ResponseUsage(input_tokens=298, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=64, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=362)),
 ({'question': 'In what way does self-awareness support intuition?',
   'document': 3,
   'score': 'good',
   'reasoning': 'The AI answer preserves the core meaning of the ground truth: self-awareness helps intuition by letting you understand your emotions and their causes, providing internal information that supports intuitive judgment. It is semantically equivalent.'},
  ResponseUsage(input_tokens=286, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=56, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=342)),
 ({'question': 'How can understanding your feelings improve the way you make choices?',
   'document': 4,
   'score': 'good',
   'reasoning': 'The AI answer preserves the core meaning of the ground truth: recognizing/understanding feelings helps you see how they influence your judgment and choices. It is semantically equivalent.'},
  ResponseUsage(input_tokens=279, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=50, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=329)),
 ({'question': 'In what way does noticing your emotions help you judge situations better?',
   'document': 4,
   'score': 'good',
   'reasoning': 'The AI answer matches the ground truth in meaning and wording. It correctly states that noticing emotions helps you see how they influence judgment and choices.'},
  ResponseUsage(input_tokens=281, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=44, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=325)),
 ({'question': "Why is it useful to recognize what you're feeling before deciding something?",
   'document': 4,
   'score': 'good',
   'reasoning': 'The AI answer preserves the core idea that recognizing feelings helps prevent them from unconsciously influencing decisions and allows more deliberate judgment. It adds related detail about regulating emotions, which is compatible with the ground truth.'},
  ResponseUsage(input_tokens=304, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=56, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=360)),
 ({'question': 'How can being aware of your emotions affect your judgment and decisions?',
   'document': 4,
   'score': 'good',
   'reasoning': 'The AI answer preserves the core meaning of the ground truth: recognizing emotions helps you see how they influence judgment and choices. The added note about better decisions is consistent and does not alter the original meaning.'},
  ResponseUsage(input_tokens=289, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=56, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=345)),
 ({'question': 'What does self-awareness do to help you make smarter choices?',
   'document': 4,
   'score': 'good',
   'reasoning': 'The AI answer preserves the core meaning of the original: self-awareness involves recognizing feelings and understanding their influence on judgment and choices, which helps improve decision-making. It is semantically equivalent and adds a mild elaboration without changing the meaning.'},
  ResponseUsage(input_tokens=287, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=63, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=350)),
 ({'question': 'How does self-awareness help act as a moral compass in daily choices?',
   'document': 5,
   'score': 'good',
   'reasoning': 'The AI answer preserves the key idea from the ground truth: self-awareness helps by recognizing feelings and internal signals that guide choices and behavior. It is semantically equivalent and adds a bit of explanatory framing without changing the meaning.'},
  ResponseUsage(input_tokens=295, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=60, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=355)),
 ({'question': 'In what way does being self-aware help you notice feelings and inner signals?',
   'document': 5,
   'score': 'good',
   'reasoning': 'The AI answer matches the original answer exactly in meaning and wording. It correctly states that self-awareness helps recognize feelings and internal signals that guide choices and behavior.'},
  ResponseUsage(input_tokens=283, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=53, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=336)),
 ({'question': 'Why is self-awareness useful for guiding behavior and decisions?',
   'document': 5,
   'score': 'good',
   'reasoning': 'The AI answer captures the core idea that self-awareness helps recognize internal feelings and signals that influence behavior and decisions. It adds some extra detail about managing emotions and noticing bias, which is consistent with the original answer and does not contradict it.'},
  ResponseUsage(input_tokens=313, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=63, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=376)),
 ({'question': 'How can knowing your own emotions make it easier to choose the right action?',
   'document': 5,
   'score': 'good',
   'reasoning': 'The AI answer preserves the core idea: self-awareness of emotions helps you notice how feelings influence judgment and choices, making action more intentional. This is semantically equivalent to recognizing internal signals that guide behavior.'},
  ResponseUsage(input_tokens=293, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=56, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=349)),
 ({'question': 'What does self-awareness let you recognize inside yourself when making choices?',
   'document': 5,
   'score': 'good',
   'reasoning': 'The AI answer matches the ground truth in meaning: it says self-awareness lets you recognize your feelings and internal signals when making choices. This preserves the key idea without distortion or omission.'},
  ResponseUsage(input_tokens=280, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=52, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=332)),
 ({'question': 'What does emotional self-management mean in simple terms?',
   'document': 6,
   'score': 'good',
   'reasoning': 'The AI answer preserves the core meaning of the ground truth: managing upsetting/distressing emotions effectively so they do not interfere with actions or tasks. It is semantically equivalent and concise.'},
  ResponseUsage(input_tokens=290, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=52, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=342)),
 ({'question': 'How would you describe emotional self-management when someone is upset?',
   'document': 6,
   'score': 'good',
   'reasoning': "The AI answer matches the original answer exactly in meaning and wording. It correctly defines emotional self-management as handling distressing emotions so they do not interfere with one's actions."},
  ResponseUsage(input_tokens=294, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=49, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=343)),
 ({'question': 'Why is emotional self-management important for staying focused on a task?',
   'document': 6,
   'score': 'good',
   'reasoning': 'The AI answer matches the ground truth in meaning. It states that emotional self-management helps handle distressing emotions so they do not interfere with the task, which is the same core idea.'},
  ResponseUsage(input_tokens=297, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=53, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=350)),
 ({'question': 'What does it look like to handle distressing emotions effectively?',
   'document': 6,
   'score': 'good',
   'reasoning': 'The AI answer preserves the core meaning of the original: effectively managing distressing emotions so they do not interfere with one’s actions. It is semantically equivalent, with only minor wording differences.'},
  ResponseUsage(input_tokens=290, input_tokens_details=InputTokensDetails(cache_write_tokens=0, cached_tokens=0), output_tokens=54, output_tokens_details=OutputTokensDetails(reasoning_tokens=0), total_tokens=344)),
 ({'question': "How can emotional self-management keep emotions from interfering with what you're doing?",
   'document': 6,
   'score': 'good',

In [62]:
evaluations = []
usages = []

for evaluation, usage in results_evaluation:
    evaluations.append(evaluation)
    usages.append(usage)

In [63]:
df_eval = pd.DataFrame(evaluations)

In [65]:
df_eval.score.value_counts()

score
good    466
bad      34
Name: count, dtype: int64

In [66]:
df_eval.score.value_counts(normalize=True)

score
good    0.932
bad     0.068
Name: proportion, dtype: float64

In [67]:
df_eval.to_csv("data/rag-evaluations-new.csv", index=False)